2020-07-27 01:52:21,490 INFO    MainThread:192 [wandb_init.py:_log_setup():335] Logging user logs to .\wandb\runs\run-20200727_015221-1aohf29e\logs\debug-20200727_015221-1aohf29e.log
2020-07-27 01:52:21,490 INFO    MainThread:192 [wandb_init.py:_log_setup():336] Logging internal logs to .\wandb\runs\run-20200727_015221-1aohf29e\logs\debug-internal-20200727_015221-1aohf29e.log
2020-07-27 01:52:21,490 INFO    MainThread:192 [wandb_setup.py:_flush():68] setting env: {}
2020-07-27 01:52:21,490 INFO    MainThread:192 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-07-27 01:52:21,492 WARNING MainThread:192 [wandb_setup.py:__init__():206] Ignoring settings passed to wandb.setup() which has already been configured.
2020-07-27 01:52:21,493 WARNING MainThread:192 [wandb_setup.py:__init__():206] Ignoring settings passed to wandb.setup() which has already been configured.
2020-07-27 01:52:21,493 WARNING MainThread:192 [wandb_setup.py:__init__():206] Ignoring settings passed to wandb.setup() which has already been configured.
2020-07-27 01:52:21,515 ERROR   MainThread:192 [wandb_init.py:init():577] we got issues
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 571, in init
    run = wi.init()
  File "C:\Program Files\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 468, in init
    use_redirect=self._use_redirect,
  File "C:\Program Files\Python\lib\site-packages\wandb\backend\backend.py", line 106, in ensure_launched
    wandb_process.start()
  File "C:\Program Files\Python\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
2020-07-27 01:52:21,517 WARNING MainThread:192 [wandb_init.py:_atexit_cleanup():340] process exited without backend configured
2020-07-27 01:52:21,517 ERROR   MainThread:192 [wandb_init.py:init():590] error
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 571, in init
    run = wi.init()
  File "C:\Program Files\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 468, in init
    use_redirect=self._use_redirect,
  File "C:\Program Files\Python\lib\site-packages\wandb\backend\backend.py", line 106, in ensure_launched
    wandb_process.start()
  File "C:\Program Files\Python\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
