  0%|                                                                           | 0/500 [00:00<?, ?it/s]  0%|                                                                           | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../metro_training.py", line 456, in <module>
  File "/home/huron/repo/METRO/src/utils/model_training_utlis_wtensorboard.py", line 255, in train_model
    for batch_idx, batch in enumerate(train_dataloader):
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/huron/.local/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/huron/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/huron/repo/METRO/src/dataloaders/uva_dar_dataset.py", line 176, in __getitem__
    seq, seq_len = self.get_video_data(idx, modality)
  File "/home/huron/repo/METRO/src/dataloaders/uva_dar_dataset.py", line 149, in get_video_data
    seq = torch.load(data_filepath).detach()
  File "/home/huron/.local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/huron/.local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/huron/.local/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/huron/.local/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/huron/.local/lib/python3.7/site-packages/torch/serialization.py", line 135, in _cuda_deserialize
    with torch.cuda.device(device):
  File "/home/huron/.local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 254, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
  File "/home/huron/.local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

